### ISSUE TITLE
Wstępny projekt specyfikacji wymagań

### ISSUE THREAD

**Issue by Tysiac1000** [Tysiac1000/Warcaby#1]
Szablon wstępny specyfikacji wymagań

**Comment by Tysiac1000** [comment]
Trzeba dokonać kliku poprawek w dokumencie, który został przygotowany. Tryb gry dla jednej osoby odpada. Jak skończysz wrzuć ten dokument to ewentualnie jeszcze poprawimy wspólnie.

**Comment by jakbuz** [comment]
Jutro na wykładach się tym zajmę,  tam jeszcze trzeba będzie wymagania
funkcjonalne/nie funkcjonalne poprawić.
4 mar 2015 20:23 "Krzysztof Matysik" notifications@github.com napisał(a):
