### ISSUE TITLE
Stworzyć kilka modeli interfejsu aplikacji

### ISSUE THREAD

**Issue by Tysiac1000** [Tysiac1000/Warcaby#4]
Do wykonania po ukończonej specyfikacji wymagań.
Prosty program do tworzenia modeli: http://pencil.evolus.vn/

**Comment by kamillo342** [comment]
Słuchaj ja nie ogarniam jakoś tego git huba
:D
I nie widze tych przykładowych co mi wysłałeś


2015-03-04 20:36 GMT+01:00 Krzysztof Matysik <notifications@github.com>:

**Comment by Tysiac1000** [comment]
Trzeba zrobić więcej modeli z ładniejszym interfejsem

**Comment by Tysiac1000** [comment]
Na wtorek MUSIMY mieć minimum 2 modele aplikacji, więc do pracy

**Comment by kamillo342** [comment]
No właśnie i co mychale dasz radę zrobić ?

**Comment by Tysiac1000** [comment]
Zrób do tego dokładny model działania samouczka
