### ISSUE TITLE
Specyfikacja wymagań (wersja finalna)

### ISSUE THREAD

**Issue by Tysiac1000** [Tysiac1000/Warcaby#5]
Czas na wykonanie: do wtorku 10 marca

**Comment by Tysiac1000** [comment]
Poprawka, do 17 marca

**Comment by Tysiac1000** [comment]
To trzeba jeszcze poprawić, Michał to dokończy

**Comment by jakbuz** [comment]
A dziś jesteście?
 30 mar 2015 14:03 "Krzysztof Matysik" notifications@github.com
napisał(a):

**Comment by Tysiac1000** [comment]
Jutro ogarniemy diagram klas w CIWE o 10:00
