### ISSUE TITLE
Diagram klas

### ISSUE THREAD

**Issue by Tysiac1000** [Tysiac1000/Warcaby#7]

**Comment by Tysiac1000** [comment]
Postaraj się dziś to dodać, to bedziemy mogli pisać już klasy i zbudować szkielet dla menu głównego

**Comment by sine-wav33** [comment]
Dzisiaj mam sporo rzeczy do zrobienia ale postaram się ogarnąć
20 mar 2015 13:19 "Krzysztof Matysik" notifications@github.com napisał(a):

**Comment by Tysiac1000** [comment]
Zrób ile możesz, zacommituj do wieczora, wszyscy bedą mieli wgląd we wstępną wersje i bedziemy mogli to tutaj dokładnie przedyskutować. Dodatkowo każdy kto ma czas mógłby poczytać o tworzeniu takich diagramów. Jeśli ktoś ma jakieś ciekawe źródło na ten temat, niech poda link.

**Comment by Tysiac1000** [comment]
Ogólnie diagram klas jest ok, tylko trzeba się jeszcze zastanowić nad funkcjonowaniem rozgrywki. Zastanowimy się nad tym w poniedziałek na którymś okienku.
